const barcelona = {
    titulo: 'Discover Barcelona: The jewel of Catalonia',
    precio: "Today's promotional price is €500 euros",
    subtitulo: 'Immerse yourself in the history, culture and beauty of this vibrant city',
    parrafo: "Welcome to Barcelona, a captivating city that perfectly combines historical richness with a modern and dynamic atmosphere. Located in the Catalonia region of northeastern Spain, Barcelona is known for its iconic architecture, vibrant art scene, delicious cuisine, and beautiful Mediterranean beaches. <br> <br> Our tour of Barcelona begins in its historic heart: the Gothic Quarter. Losing yourself in its narrow cobbled streets, you will discover impressive medieval buildings, ancient churches and charming squares full of life. You cannot miss visiting the majestic Cathedral of Barcelona, a magnificent example of Gothic architecture.<br> <br> As you enter the city, you will marvel at the architectural masterpieces of Antoni Gaudí, one of the greatest exponents of Catalan modernism. The Sagrada Familia, His unfinished masterpiece will leave you speechless with its unique design and ornamental details. Other Gaudí treasures include Park Güell, with its colorful mosaics and panoramic views of the city, and Casa Batlló, a modernist building that looks like something out of a fairy tale.<br> <br> Barcelona is also famous for its passion for football. If you are a lover of this sport, you cannot miss the Camp Nou, the stadium of FC Barcelona. Immerse yourself in the passionate atmosphere of a match and discover the history of the club in its museum.<br> <br> But Barcelona is not just about architecture and sport. The city has a bustling cultural scene, with a wide variety of museums, art galleries and cultural events. The Picasso Museum houses an impressive collection of works by the famous Spanish painter, while the MACBA and the CCCB are spaces dedicated to contemporary art and urban culture.<br> <br> When you need a break, head to the beaches of Barcelona. Relax under the Mediterranean sun, enjoy a refreshing swim in the sea and try local delicacies at beach bars. <br> <br> Barcelona is also known for its lively nightlife. From traditional bars and taverns to world-renowned nightclubs and discotheques, the city offers options for all tastes. Stroll through the streets of the lively El Born neighborhood or enjoy a drink at the beach bars.<br> <br> In short, Barcelona is a fascinating city that offers a perfect combination of history, culture, architecture and entertainment. Get ready to get lost in its charms, savor its gastronomy, Enjoy its energy and take home unforgettable memories. Discover Barcelona and let yourself be captivated by its magic!"
}

const rome = {
    titulo: 'Rome: Eternal Treasures in the Eternal City',
    precio: "Today's promotional price is €400 euros",
    subtitulo: 'Immerse yourself in the historical grandeur, art and culture of the Italian capital',
    parrafo: "Welcome to Rome, a city that breathes history and that will transport you through the centuries. Known as the Eternal City, Rome is home to an unrivaled wealth of ancient monuments, Renaissance art and a vibrant culture that will captivate you from the first moment. <br> <br> Our journey through Rome begins in the heart of ancient Rome: the Colosseum. This imposing amphitheater is one of the most iconic architectural wonders in the world and will take your breath away with its magnificence. Imagine the exciting gladiatorial combats and theatrical performances that once took place in this legendary place.<br> <br> Just a few steps from the Colosseum, you will discover the Roman Forum, the political and social center of ancient Rome. Tour the ruins of ancient temples, triumphal arches and basilicas, and let yourself be carried away by the majesty of this place full of history. <br> <br> Continuing our tour, we head to the Vatican, the smallest independent enclave in the world and the spiritual heart of Catholicism. St. Peter's Basilica, with its iconic dome designed by Michelangelo, will impress you with its beauty and splendor. Don't forget to also visit the Vatican Museums, where you can admire an impressive collection of art, including the famous Sistine Chapel, with its frescoes created by great Renaissance artists.<br> <br> Rome is also known for its charming squares and fountains. Piazza Navona, with its baroque architecture and its famous Fountain of the Four Rivers, invites you to relax and enjoy the Roman atmosphere. The Trevi Fountain, the city's most famous fountain, is a must-see place to toss a coin and ensure you return to Rome in the future.<br> <br> Strolling through the cobblestone streets of Trastevere will immerse you in the authentic Roman life. Discover its charming squares, its colorful facades and its lively bars and restaurants, where you can try delicious Italian cuisine.<br> <br> Rome is also famous for its catacombs, vast underground tunnel systems and burial chambers. Explore the catacombs of Saint Callixtus or the catacombs of Saint Sebastian and discover this fascinating legacy of ancient Rome.<br> <br> In short, Rome is a city that will transport you back in time and immerse you in an unrivaled wealth of history , art and culture. From its ancient monuments to its charming squares and delicious cuisine, every corner of Rome has a story to tell. Prepare to marvel at the grandeur of the Eternal City and be captivated by its timeless charm."
}

const paris = {
    titulo: 'Paris: The City of Light and Romance',
    precio: "Today's promotional price is €550 euros",
    subtitulo: 'Explore the elegance, culture and charm of the French capital',
    parrafo: "Welcome to Paris, a city that has captivated visitors from all over the world with its beauty, elegance and romance. Known as the City of Light, Paris offers a unique blend of history, art, culture and gastronomy that makes it a truly unforgettable destination. <br> <br> Our journey through Paris begins in the heart of the city, at the iconic Eiffel Tower. This iconic structure, built for the 1889 World's Fair, will give you a stunning panoramic view of the city. Whether you decide to climb to the top or simply admire it from the ground, the Eiffel Tower is an unmistakable symbol of Paris. <br> <br> Continuing our tour, we enter the charming Montmartre neighborhood, known for its bohemian atmosphere and picturesque beauty. Explore its narrow cobblestone streets and reach the imposing Basilica of the Sacred Heart, which offers panoramic views of the city. Don't forget to visit the famous Moulin Rouge cabaret and enjoy a show full of energy and glamour. <br> <br> The next destination is the Louvre, one of the largest and most famous museums in the world. Admire masterpieces such as the Mona Lisa and the Venus de Milo, while marveling at the grandeur of the Louvre Palace, an architectural gem in itself. Touring its galleries is immersing yourself in the history of art and culture. <br> <br> Crossing the Seine River takes us to the charming neighborhood of Saint-Germain-des-Prés, known for its bookstores, historic cafes and intellectual atmosphere. Immerse yourself in Parisian culture while enjoying a coffee at the famous Café de Flore or exploring the area's fashion stores and art galleries. <br> <br> The charm of Paris extends to its exquisite gardens. The Luxembourg Garden and the Tuileries Garden are oases of peace and beauty, where you can relax and enjoy serenity in the middle of the bustling city. Take a romantic walk along its flower-lined paths or enjoy a quiet picnic under the shade of the trees. <br> <br> You can't visit Paris without exploring the charming Île de la Cité, home to the famous Notre Dame Cathedral. This Gothic masterpiece, with its stunning architecture and beautiful stained glass windows, will transport you to times gone by. Although the cathedral suffered a fire in 2019, its grandeur remains captivating and its reconstruction is underway. <br> <br> In short, Paris is a city that envelops you with its elegance, culture and romance. From its iconic monuments to its charming neighborhoods, the French capital offers a unique experience full of history and charm."
}

const london = {
    titulo: 'London: Discover the magic of the City of the Thames',
    precio: "Today's promotional price is €600 euros",
    subtitulo: 'Immerse yourself in the history, diversity and energy of the British capital',
    parrafo: "Welcome to London, a vibrant city that fuses its rich history with a contemporary and diverse scene. Known as the City of the Thames, London will captivate you with its charm, its cultural heritage and its cosmopolitan spirit. <br> <br> Our London tour begins at the iconic Buckingham Palace, the official residence of the Queen of England. If you're lucky, you'll be able to witness the changing of the guard, a traditional ceremony full of pomp and color. From there, you can stroll through the nearby St. James Park and enjoy the serenity of its gardens. <br> <br> Continuing our journey, we arrive at the historic heart of London: the Tower of London. This iconic castle bears witness to centuries of history and houses the British Crown Jewels. Explore its fortified walls and discover the stories of intrigue, betrayal and mysteries that surround this place. <br> <br> Crossing Tower Bridge, one of the most recognized symbols of the city, we enter the bustling Southbank. Here you'll find a wide range of cultural attractions, including the Tate Modern, a contemporary art museum, and the London Eye, a giant Ferris wheel that offers stunning panoramic views of the city. <br> <br> London is also famous for its world-class museums. The British Museum, with its impressive collection of artefacts and antiquities from around the world, is a treasure not to be missed. You cannot miss the opportunity to visit the Natural History Museum, with its famous dinosaur skeleton and its impressive collection of specimens. <br> <br> If you are passionate about art, the Tate Britain and the National Gallery will delight you with masterpieces by artists such as Turner, Van Gogh and Rembrandt. In addition, theater lovers cannot miss the famous West End, the district of musicals and plays, where you will find world-renowned shows. <br> <br> London is known for its diversity and multicultural atmosphere. Explore the neighborhoods of Camden Town and Notting Hill, where you'll find street markets, vintage shops and a wide range of international cuisine. Don't forget to try the famous British fish and chips, enjoy tea in a traditional tea house and visit London's charming pubs. <br> <br> In short, London is a city that combines history, culture and modernity in a unique way. From its iconic monuments to its lively neighborhoods, the British capital invites you to discover its magic and immerse yourself in its contagious energy. Explore London and let yourself be carried away by its fascinating charm!"
}



export {
    barcelona,
    rome,
    paris,
    london
};

// const { barcelona, roma, paris, londres } = require('./ciudades');

//ES6
// export { objeto1, objeto2 };
//import { objeto1, objeto2 } from './ciudades';
